[workspace]
authors = ["nathanweisz <nathanweisz@me.com>"]
channels = ["conda-forge"]
name = "MethodsCogNeuro"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
mne = ">=1.10.2,<2"
pandas = ">=2.3.3,<3"
ipython = ">=9.7.0,<10"
seaborn = ">=0.13.2,<0.14"
pip = ">=25.3,<26"
mne-connectivity = ">=0.7.0,<0.8"
matplotlib = ">=3.10.8,<4"
numpy = ">=2.3.5,<3"
scipy = ">=1.16.3,<2"

[pypi-dependencies]
mtrf = ">=2.1.2, <3"

